name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd secretstroll
        chmod 777 tor
        docker compose build
        docker compose up -d
        docker exec --workdir /server cs523-server chmod 700 /var/lib/tor/hidden_service/
        docker exec -d --workdir /server cs523-server python3 server.py run
        docker exec --workdir /client cs523-client pip install -r requirements.txt
        docker exec --workdir /client cs523-client pytest test_stroll.py
        docker compose down
