# This is a basic workflow to help you get started with Actions

name: PyTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# source https://www.techiediaries.com/python-unit-tests-github-actions/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd secretstroll
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: |
          cd secretstroll && python3 -m pytest -v --count=100 -n 4
   
